POST localhost:8004/api/product/admin/book/register
Content-Type: application/json

{
  "title": "제목5",
  "publisher": "출판사",
  "author": "작가",
  "pubDate": "2024-06-20",
  "isbn": "isbnisbn15",
  "isbn13": "isbnisbnisbn5",
  "cover": "cover",
  "productName": "product5",
  "packable": false,
  "productDescription": "설명5",
  "productInventory": 101,
  "productPriceStandard": 500001,
  "productPriceSales": 100001,
  "categories": [
    "카테고리4"
  ],
  "tags": [
    "tag5", "tag4"
  ]
}

###
GET localhost:8004/api/product/book/1

###
PUT localhost:8004/api/product/admin/book/update
Content-Type: application/json

{
  "bookId": 1,
  "productName": "product changed",
  "packable": true,
  "productDescription": "changed description",
  "productInventory": 1023,
  "productPriceSales": 100,
  "productState": 0,
  "categories": [
    "카테고리3"
  ],
  "tags": [
    "tag2", "tag1", "tag3"
  ]
}