POST localhost:8004/api/admin/category/register
Content-Type: application/json

{
  "categoryName": "카테고리3"
}

###
GET localhost:8004/api/admin/category/test
Content-Type: application/json

{
 "page": 1,
  "sort": "wrong"
}

###
PUT localhost:8004/api/admin/category
Content-Type: application/json

{
  "currentCategoryName": "카테고리3",
  "newCategoryName": "뉴카테고리3"
}