POST localhost:8004/api/product/admin/category/register
Content-Type: application/json

{
  "categoryName": "카테345678",
  "parentCategoryName": "카테고리2"
}

###
GET localhost:8004/api/product/categories/sub?categoryName=카테고리5&sort=wrongsad

###
GET localhost:8004/api/product/categories/all?sort=parentProductCateasdgory&desc=false

###
GET localhost:8004/api/product/categories/containing?categoryName=2&sort=parentProductCategory



###
PUT localhost:8004/api/product/admin/category/update
Content-Type: application/json

{
  "currentCategoryName": "카테고리3",
  "newCategoryName": "뉴카테고리"
}