POST localhost:8004/api/product/admin/tag/register
Content-Type: application/json

{
  "tagName": "tag1"
}

###
GET localhost:8004/api/product/tags/containing?tagName=1&sort=asdasd
Content-Type: application/json

{

}

####
PUT localhost:8004/api/admin/tag
Content-Type: application/json

{
  "currentTagName": "tag2",
  "newTagName": "newTag2"
}